export const pagesRoutes = [
  ["v-147825fb","/docs/",{"title":""},["/docs/index.html","/docs/README.md"]],
  ["v-0f6ce3bf","/docs/home.html",{"title":"安陽1928"},["/docs/home","/docs/home.md"]],
  ["v-b9c4336a","/docs/news.html",{"title":"報道"},["/docs/news","/docs/news.md"]],
  ["v-f42f0c40","/docs/huanbei-shang-city/",{"title":"洹北商城"},["/docs/huanbei-shang-city/index.html","/docs/huanbei-shang-city/README.md"]],
  ["v-4b6eb376","/docs/huanbei-shang-city/report.html",{"title":"報告"},["/docs/huanbei-shang-city/report","/docs/huanbei-shang-city/report.md"]],
  ["v-672ca53c","/docs/note/",{"title":"筆記"},["/docs/note/index.html","/docs/note/README.md"]],
  ["v-3cc76957","/docs/note/terrin-model-in-gis.html",{"title":"ArcGIS處理激光雷達模型"},["/docs/note/terrin-model-in-gis","/docs/note/terrin-model-in-gis.md"]],
  ["v-dca627d4","/docs/oracle/",{"title":"甲骨"},["/docs/oracle/index.html","/docs/oracle/README.md"]],
  ["v-c294ce8e","/docs/oracle/article.html",{"title":"論文"},["/docs/oracle/article","/docs/oracle/article.md"]],
  ["v-77709cae","/docs/yearbook/",{"title":"年鑒"},["/docs/yearbook/index.html","/docs/yearbook/README.md"]],
  ["v-4391b007","/docs/yearbook/new-archaeological-discovery.html",{"title":"考古新發現"},["/docs/yearbook/new-archaeological-discovery","/docs/yearbook/new-archaeological-discovery.md"]],
  ["v-598b5322","/docs/yinxu/",{"title":"殷墟"},["/docs/yinxu/index.html","/docs/yinxu/README.md"]],
  ["v-21014592","/docs/yinxu/article.html",{"title":"論文"},["/docs/yinxu/article","/docs/yinxu/article.md"]],
  ["v-929eab54","/docs/yinxu/report.html",{"title":"報告"},["/docs/yinxu/report","/docs/yinxu/report.md"]],
  ["v-3706649a","/404.html",{"title":""},["/404"]],
]
